"""Agregar modelos de Tratamiento

Revision ID: 5303954ce265
Revises: bcca87dbf48d
Create Date: 2026-06-09 13:13:09.207484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5303954ce265'
down_revision = 'bcca87dbf48d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tratamientos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consulta_id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('medico_id', sa.Integer(), nullable=False),
    sa.Column('diagnostico_completo', sa.Text(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['consulta_id'], ['consultas.id'], ),
    sa.ForeignKeyConstraint(['medico_id'], ['medicos.id'], ),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tratamiento_sesiones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tratamiento_id', sa.Integer(), nullable=False),
    sa.Column('numero_sesion', sa.Integer(), nullable=False),
    sa.Column('cita_id', sa.Integer(), nullable=True),
    sa.Column('consulta_realizada_id', sa.Integer(), nullable=True),
    sa.Column('venta_id', sa.Integer(), nullable=True),
    sa.Column('fecha_programada', sa.Date(), nullable=False),
    sa.Column('hora_programada', sa.Time(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['cita_id'], ['citas.id'], ),
    sa.ForeignKeyConstraint(['consulta_realizada_id'], ['consultas.id'], ),
    sa.ForeignKeyConstraint(['tratamiento_id'], ['tratamientos.id'], ),
    sa.ForeignKeyConstraint(['venta_id'], ['ventas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tratamiento_sesion_procedimientos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sesion_id', sa.Integer(), nullable=False),
    sa.Column('procedimiento_id', sa.Integer(), nullable=False),
    sa.Column('precio_planificado', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['procedimiento_id'], ['procedimientos.id'], ),
    sa.ForeignKeyConstraint(['sesion_id'], ['tratamiento_sesiones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tratamiento_sesion_procedimientos')
    op.drop_table('tratamiento_sesiones')
    op.drop_table('tratamientos')
    # ### end Alembic commands ###
