"""Add codigo and categoria to insumos; stock property compatibility

Revision ID: 9ce7b2a4c12f
Revises: c3f616b8e08e
Create Date: 2025-12-23 13:46:14.872936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ce7b2a4c12f'
down_revision = 'c3f616b8e08e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('insumos', schema=None) as batch_op:
        # Add 'codigo' (nullable) and 'categoria' with a safe server_default so
        # existing rows receive a non-null value (avoids ALTER ... NOT NULL failure)
        batch_op.add_column(sa.Column('codigo', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('categoria', sa.String(length=50), nullable=False, server_default=sa.text("'consumible'")))

    # remove the server_default after the column is added so future inserts
    # don't implicitly get that default unless explicitly desired
    op.alter_column('insumos', 'categoria', server_default=None)

    with op.batch_alter_table('pacientes', schema=None) as batch_op:
        batch_op.drop_column('tipo_documento')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pacientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_documento', sa.VARCHAR(length=20), autoincrement=False, nullable=True))

    with op.batch_alter_table('insumos', schema=None) as batch_op:
        batch_op.drop_column('categoria')
        batch_op.drop_column('codigo')

    # ### end Alembic commands ###
