"""Hacer motivo y diagnostico opcionales en consultas

Revision ID: bcca87dbf48d
Revises: 20260330odontograma
Create Date: 2026-04-07 11:28:00.528245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcca87dbf48d'
down_revision = '20260330odontograma'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Removed drop_constraint for asistencias as it doesn't exist
    with op.batch_alter_table('asistencias', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'usuarios', ['usuario_id'], ['id'])

    with op.batch_alter_table('consultas', schema=None) as batch_op:
        batch_op.alter_column('motivo',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('diagnostico',
               existing_type=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('especialidades', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_especialidades_usuario'), type_='foreignkey')
        batch_op.drop_column('usuario_id')

    with op.batch_alter_table('horarios_atencion', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_horarios_atencion_especialidad'), type_='foreignkey')
        batch_op.drop_column('especialidad_id')

    with op.batch_alter_table('insumo_especialidades', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_insumo_especialidades_usuario'), type_='foreignkey')
        batch_op.drop_column('usuario_id')

    with op.batch_alter_table('permisos', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'usuarios', ['usuario_id'], ['id'])

    with op.batch_alter_table('procedimiento_precios', schema=None) as batch_op:
        batch_op.drop_column('usuario_id')

    with op.batch_alter_table('vacaciones', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'usuarios', ['usuario_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vacaciones', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_vacaciones_usuario'), 'usuarios', ['usuario_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('procedimiento_precios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_procedimiento_precios_usuario'), 'usuarios', ['usuario_id'], ['id'])

    with op.batch_alter_table('permisos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_permisos_usuario'), 'usuarios', ['usuario_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('insumo_especialidades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_insumo_especialidades_usuario'), 'usuarios', ['usuario_id'], ['id'])

    with op.batch_alter_table('horarios_atencion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('especialidad_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_horarios_atencion_especialidad'), 'especialidades', ['especialidad_id'], ['id'])

    with op.batch_alter_table('especialidades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_especialidades_usuario'), 'usuarios', ['usuario_id'], ['id'])

    with op.batch_alter_table('consultas', schema=None) as batch_op:
        batch_op.alter_column('diagnostico',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('motivo',
               existing_type=sa.TEXT(),
               nullable=False)

    with op.batch_alter_table('asistencias', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_asistencias_usuario'), 'usuarios', ['usuario_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
