"""Add billing fields to Paciente

Revision ID: c3f616b8e08e
Revises: cc3824205748
Create Date: 2025-12-23 10:12:34.107554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3f616b8e08e'
down_revision = 'cc3824205748'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pacientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_documento', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('condicion_tributaria', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('ciudad', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pacientes', schema=None) as batch_op:
        batch_op.drop_column('ciudad')
        batch_op.drop_column('condicion_tributaria')
        batch_op.drop_column('tipo_documento')

    # ### end Alembic commands ###
