"""Add ProcedimientoPrecio (precios por medico/especialidad)

Revision ID: cc3824205748
Revises: 
Create Date: 2025-12-23 09:11:03.276195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc3824205748'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('procedimiento_precios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('procedimiento_id', sa.Integer(), nullable=False),
    sa.Column('medico_id', sa.Integer(), nullable=True),
    sa.Column('especialidad_id', sa.Integer(), nullable=True),
    sa.Column('precio', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['especialidad_id'], ['especialidades.id'], ),
    sa.ForeignKeyConstraint(['medico_id'], ['medicos.id'], ),
    sa.ForeignKeyConstraint(['procedimiento_id'], ['procedimientos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('insumos', schema=None) as batch_op:
        batch_op.alter_column('precio_compra',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('ventas', schema=None) as batch_op:
        batch_op.alter_column('nombre_factura',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ventas', schema=None) as batch_op:
        batch_op.alter_column('nombre_factura',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)

    with op.batch_alter_table('insumos', schema=None) as batch_op:
        batch_op.alter_column('precio_compra',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True,
               existing_server_default=sa.text('0'))

    op.drop_table('procedimiento_precios')
    # ### end Alembic commands ###
