"""Hacer caja_id opcional en ventas

Revision ID: f44cc4a7596e
Revises: 5ad1e236d813
Create Date: 2025-12-29 13:15:36.376761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f44cc4a7596e'
down_revision = '5ad1e236d813'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ventas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('direccion_facturacion', sa.Text(), nullable=True))
        batch_op.alter_column('caja_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('direccion_factura')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ventas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('direccion_factura', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.alter_column('caja_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('direccion_facturacion')

    # ### end Alembic commands ###
